package cmd

import (
	"fmt"
	"strings"

	"github.com/echoja/english-punch-app/cli/internal/ep/common"
	"github.com/spf13/cobra"
)

var cardsCreateFields = []common.Field{
	{Name: "bagId", Type: "string"},
	{Name: "question", Type: "string"},
	{Name: "answer", Type: "string"},
	{Name: "hint", Type: "string"},
	{Name: "explanation", Type: "string"},
}

func newCardsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "cards",
		Short: "Manage flashcards",
		Long: `Create and (eventually) list/update/delete individual
flashcards. The CLI is a thin wrapper around the Convex
learning:* mutations — card content (question, hint, explanation)
is generated by the caller, not by the CLI.`,
	}

	cmd.AddCommand(newCardsCreateCmd())

	return cmd
}

func newCardsCreateCmd() *cobra.Command {
	var (
		bagID       string
		question    string
		hint        string
		explanation string
	)

	cmd := &cobra.Command{
		Use:   "create <answer>",
		Short: "Create a flashcard from caller-provided fields",
		Long: `Create a flashcard by passing every field on the command
line. ep does not call Gemini or any other AI — the caller (a
Claude Code skill in the primary use case) is expected to generate
the question, hint, and explanation itself following the rules in
convex/ai.ts, then pass them as flags.

This is the LLM-as-caller form of card creation: zero Gemini cost
at the CLI layer, a single Convex mutation round-trip, fully
parseable JSON output, and pattern-matchable MISSING_REQUIRED_FIELD
tokens for the skill to branch on.

The --bag flag is optional and falls back to default_bag_id in the
config file (set via 'ep bags default set'). Bag ownership is not
pre-verified — the server will reject an unauthorized bag id on
the createCard mutation.`,
		Example: `  # Happy path: every field supplied, default bag from config
  ep cards create "disheartened" \
    --question "I felt ___ after the long rejection letter arrived." \
    --hint "extremely discouraged or low-spirited" \
    --explanation "Stronger than 'sad' but softer than 'devastated'; …"

  # Explicit bag
  ep cards create "disheartened" --bag k17abc... \
    --question "..." --hint "..." --explanation "..."

  # JSON output (emits {"ok": true, "bagId": ..., "question": ..., ...})
  ep cards create "disheartened" --json \
    --question "..." --hint "..." --explanation "..."

  # JSON field filter
  ep cards create "disheartened" --json ok,bagId \
    --question "..." --hint "..." --explanation "..."`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			answer := strings.TrimSpace(args[0])
			if answer == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"answer is required",
					nil,
				)
			}
			if strings.TrimSpace(question) == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"--question is required",
					nil,
				)
			}
			if strings.TrimSpace(hint) == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"--hint is required",
					nil,
				)
			}
			if strings.TrimSpace(explanation) == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"--explanation is required",
					nil,
				)
			}

			resolvedBag, err := resolveBagID(bagID)
			if err != nil {
				return err
			}

			// --json discovery short-circuit — match the existing
			// bags list / auth status pattern so the skill can
			// discover field names without side effects.
			if jsonFlag.Used && len(jsonFlag.Fields) == 0 {
				common.PrintFieldList(append(
					[]common.Field{{Name: "ok", Type: "boolean"}},
					cardsCreateFields...,
				))
				return nil
			}

			ctx := cmd.Context()

			client, user, err := authenticatedClient(ctx)
			if err != nil {
				return err
			}

			if _, err := client.Mutation(ctx, "learning:createCard", map[string]any{
				"bagId":       resolvedBag,
				"userId":      user.ID,
				"question":    strings.TrimSpace(question),
				"answer":      answer,
				"hint":        strings.TrimSpace(hint),
				"explanation": strings.TrimSpace(explanation),
			}); err != nil {
				return err
			}

			payload := map[string]any{
				"bagId":       resolvedBag,
				"question":    strings.TrimSpace(question),
				"answer":      answer,
				"hint":        strings.TrimSpace(hint),
				"explanation": strings.TrimSpace(explanation),
			}
			if handled, err := jsonFlag.HandleOKOutput(payload, cardsCreateFields); handled {
				return err
			}

			fmt.Printf("Created card in bag %s:\n", resolvedBag)
			fmt.Printf("  Q: %s\n", strings.TrimSpace(question))
			fmt.Printf("  A: %s\n", answer)
			fmt.Printf("  Hint: %s\n", strings.TrimSpace(hint))
			return nil
		},
	}

	cmd.Flags().StringVar(&bagID, "bag", "", "Target bag ID. Falls back to default_bag_id in the config file.")
	cmd.Flags().StringVar(&question, "question", "", "Fill-in-the-blank question with ___ for the answer. Required.")
	cmd.Flags().StringVar(&hint, "hint", "", "Short definition or synonym, under 12 words. Required.")
	cmd.Flags().StringVar(&explanation, "explanation", "", "Usage/scenario/nuance note, 10-70 words. Required.")

	return cmd
}
