package cmd

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/echoja/english-punch-app/cli/internal/ep/common"
	"github.com/spf13/cobra"
)

var cardsCreateFields = []common.Field{
	{Name: "cardId", Type: "string"},
	{Name: "bagId", Type: "string"},
	{Name: "question", Type: "string"},
	{Name: "answer", Type: "string"},
	{Name: "hint", Type: "string"},
	{Name: "explanation", Type: "string"},
}

var cardsGetFields = []common.Field{
	{Name: "cardId", Type: "string"},
	{Name: "bagId", Type: "string"},
	{Name: "question", Type: "string"},
	{Name: "answer", Type: "string"},
	{Name: "hint", Type: "string"},
	{Name: "explanation", Type: "string"},
	{Name: "context", Type: "string"},
	{Name: "sourceWord", Type: "string"},
	{Name: "expression", Type: "string"},
}

var cardsListFields = []common.Field{
	{Name: "bagId", Type: "string"},
	{Name: "search", Type: "string"},
	{Name: "count", Type: "number"},
	{Name: "isDone", Type: "boolean"},
	{Name: "continueCursor", Type: "string"},
	{Name: "page", Type: "object[]"},
}

var cardsReplaceFields = []common.Field{
	{Name: "cardId", Type: "string"},
	{Name: "bagId", Type: "string"},
	{Name: "question", Type: "string"},
	{Name: "answer", Type: "string"},
	{Name: "hint", Type: "string"},
	{Name: "explanation", Type: "string"},
	{Name: "context", Type: "string"},
	{Name: "sourceWord", Type: "string"},
	{Name: "expression", Type: "string"},
}

var cardsDeleteFields = []common.Field{
	{Name: "cardId", Type: "string"},
	{Name: "bagId", Type: "string"},
}

var (
	cardsResolveBagIDFunc                       = resolveBagID
	cardsAuthenticatedClientFunc                = authenticatedClient
	cardsGetCardFunc                            = getCard
	cardsListCardsFunc                          = listCards
	cardsReplaceCardContentAndResetScheduleFunc = replaceCardContentAndResetSchedule
)

func newCardsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "cards",
		Short: "Manage flashcards",
		Long: `Create, list, inspect, replace, and delete individual flashcards.
The CLI is a thin wrapper around Convex learning:* functions — card
content (question, hint, explanation) is generated by the caller, not
by the CLI.`,
	}

	cmd.AddCommand(newCardsCreateCmd())
	cmd.AddCommand(newCardsListCmd())
	cmd.AddCommand(newCardsGetCmd())
	cmd.AddCommand(newCardsReplaceCmd())
	cmd.AddCommand(newCardsDeleteCmd())

	return cmd
}

func newCardsListCmd() *cobra.Command {
	var (
		bagID  string
		search string
		cursor string
		limit  int
	)

	cmd := &cobra.Command{
		Use:   "list",
		Short: "List cards in a bag",
		Long: `List one paginated page of cards from a bag using the same
learning:getBagCardsPaginated query as the web BagDetailPage.

By default this returns the first 30 cards ordered by creation time
descending. Pass --cursor with the previous response's continueCursor
to load the next page. Pass --search to filter by answer using the
same answer search index as the web app; it does not search question,
hint, or explanation text.`,
		Example: `  ep cards list --bag k17abc...
  ep cards list --bag k17abc... --search precision
  ep cards list --bag k17abc... --limit 50 --cursor 07c...
  ep cards list --bag k17abc... --json page,continueCursor,isDone`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if limit < 1 || limit > 100 {
				return common.NewTokenError(
					common.TokenInvalidArgument,
					"--limit must be between 1 and 100",
					nil,
				)
			}

			resolvedBag, err := cardsResolveBagIDFunc(bagID)
			if err != nil {
				return err
			}

			if jsonFlag.Used && len(jsonFlag.Fields) == 0 {
				common.PrintFieldList(cardsListFields)
				return nil
			}

			ctx := cmd.Context()
			client, user, err := cardsAuthenticatedClientFunc(ctx)
			if err != nil {
				return err
			}

			result, err := cardsListCardsFunc(ctx, client, cardListOptions{
				BagID:  resolvedBag,
				UserID: user.ID,
				Search: strings.TrimSpace(search),
				Limit:  limit,
				Cursor: strings.TrimSpace(cursor),
			})
			if err != nil {
				return err
			}

			if handled, err := jsonFlag.HandleOutput(result, cardsListFields); handled {
				return err
			}

			return common.PrintJSON(result)
		},
	}

	cmd.Flags().StringVar(&bagID, "bag", "", "Target bag ID. Falls back to default_bag_id in the config file.")
	cmd.Flags().StringVar(&search, "search", "", "Search card answers using the same answer search index as the web app.")
	cmd.Flags().StringVar(&cursor, "cursor", "", "Continuation cursor returned by a previous list response.")
	cmd.Flags().IntVar(&limit, "limit", 30, "Maximum number of cards to return, from 1 to 100.")
	return cmd
}

func newCardsCreateCmd() *cobra.Command {
	var (
		bagID       string
		question    string
		hint        string
		explanation string
	)

	cmd := &cobra.Command{
		Use:   "create <answer>",
		Short: "Create a flashcard from caller-provided fields",
		Long: `Create a flashcard by passing every field on the command
line. ep does not call Gemini or any other AI — the caller (a
Claude Code skill in the primary use case) is expected to generate
the question, hint, and explanation itself following the rules in
convex/ai.ts, then pass them as flags.

This is the LLM-as-caller form of card creation: zero Gemini cost
at the CLI layer, a single Convex mutation round-trip, fully
parseable JSON output, and pattern-matchable MISSING_REQUIRED_FIELD
tokens for the skill to branch on.

The --bag flag is optional and falls back to default_bag_id in the
config file (set via 'ep bags default set'). Bag ownership is not
pre-verified — the server will reject an unauthorized bag id on
the createCard mutation.`,
		Example: `  # Happy path: every field supplied, default bag from config
  ep cards create "disheartened" \
    --question "I felt ___ after the long rejection letter arrived." \
    --hint "extremely discouraged or low-spirited" \
    --explanation "Stronger than 'sad' but softer than 'devastated'; …"

  # Explicit bag
  ep cards create "disheartened" --bag k17abc... \
    --question "..." --hint "..." --explanation "..."

  # JSON output (emits {"ok": true, "bagId": ..., "question": ..., ...})
  ep cards create "disheartened" --json \
    --question "..." --hint "..." --explanation "..."

  # JSON field filter
  ep cards create "disheartened" --json ok,bagId \
    --question "..." --hint "..." --explanation "..."`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			answer := strings.TrimSpace(args[0])
			if answer == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"answer is required",
					nil,
				)
			}
			if strings.TrimSpace(question) == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"--question is required",
					nil,
				)
			}
			if strings.TrimSpace(hint) == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"--hint is required",
					nil,
				)
			}
			if strings.TrimSpace(explanation) == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"--explanation is required",
					nil,
				)
			}

			resolvedBag, err := resolveBagID(bagID)
			if err != nil {
				return err
			}

			// --json discovery short-circuit — match the existing
			// bags list / auth status pattern so the skill can
			// discover field names without side effects.
			if jsonFlag.Used && len(jsonFlag.Fields) == 0 {
				common.PrintFieldList(append(
					[]common.Field{{Name: "ok", Type: "boolean"}},
					cardsCreateFields...,
				))
				return nil
			}

			ctx := cmd.Context()

			client, user, err := authenticatedClient(ctx)
			if err != nil {
				return err
			}

			raw, err := client.Mutation(ctx, "learning:createCard", map[string]any{
				"bagId":       resolvedBag,
				"userId":      user.ID,
				"question":    strings.TrimSpace(question),
				"answer":      answer,
				"hint":        strings.TrimSpace(hint),
				"explanation": strings.TrimSpace(explanation),
			})
			if err != nil {
				return err
			}

			var cardID string
			if err := json.Unmarshal(raw, &cardID); err != nil {
				return fmt.Errorf("parse createCard response: %w", err)
			}

			payload := map[string]any{
				"cardId":      cardID,
				"bagId":       resolvedBag,
				"question":    strings.TrimSpace(question),
				"answer":      answer,
				"hint":        strings.TrimSpace(hint),
				"explanation": strings.TrimSpace(explanation),
			}
			if handled, err := jsonFlag.HandleOKOutput(payload, cardsCreateFields); handled {
				return err
			}

			fmt.Printf("Created card %s in bag %s:\n", cardID, resolvedBag)
			fmt.Printf("  Q: %s\n", strings.TrimSpace(question))
			fmt.Printf("  A: %s\n", answer)
			fmt.Printf("  Hint: %s\n", strings.TrimSpace(hint))
			return nil
		},
	}

	cmd.Flags().StringVar(&bagID, "bag", "", "Target bag ID. Falls back to default_bag_id in the config file.")
	cmd.Flags().StringVar(&question, "question", "", "Fill-in-the-blank question with ___ for the answer. Required.")
	cmd.Flags().StringVar(&hint, "hint", "", "Short definition or synonym, under 12 words. Required.")
	cmd.Flags().StringVar(&explanation, "explanation", "", "Usage/scenario/nuance note, 10-70 words. Required.")

	return cmd
}

func cardOutputPayload(card cardDetail, bagID string) map[string]any {
	payload := map[string]any{
		"cardId":   card.ID,
		"bagId":    bagID,
		"question": card.Question,
		"answer":   card.Answer,
	}
	if card.Hint != nil {
		payload["hint"] = *card.Hint
	}
	if card.Explanation != nil {
		payload["explanation"] = *card.Explanation
	}
	if card.Context != nil {
		payload["context"] = *card.Context
	}
	if card.SourceWord != nil {
		payload["sourceWord"] = *card.SourceWord
	}
	if card.Expression != nil {
		payload["expression"] = *card.Expression
	}
	return payload
}

func printCardOutput(card cardDetail, bagID string) {
	payload := cardOutputPayload(card, bagID)
	fmt.Printf("cardId: %s\n", payload["cardId"])
	fmt.Printf("bagId: %s\n", payload["bagId"])
	fmt.Printf("question: %s\n", payload["question"])
	fmt.Printf("answer: %s\n", payload["answer"])
	for _, key := range []string{"hint", "explanation", "context", "sourceWord", "expression"} {
		if value, ok := payload[key]; ok {
			fmt.Printf("%s: %s\n", key, value)
		}
	}
}

func newCardsGetCmd() *cobra.Command {
	var bagID string

	cmd := &cobra.Command{
		Use:   "get <card-id>",
		Short: "Inspect a flashcard",
		Long: `Fetch a single flashcard from the target bag. The command
prints the study content and metadata that the skill needs before
replacing a card while preserving context.

The --bag flag is optional and falls back to default_bag_id in the
config file. Use --json for machine-readable output.`,
		Example: `  ep cards get kx78x72vmrhxft4gdd38z7s4yd81bscy
  ep cards get kx78x72vmrhxft4gdd38z7s4yd81bscy --bag k17abc...
  ep cards get kx78x72vmrhxft4gdd38z7s4yd81bscy --json
  ep cards get kx78x72vmrhxft4gdd38z7s4yd81bscy --json question,hint,context`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cardID := strings.TrimSpace(args[0])
			if cardID == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"card-id is required",
					nil,
				)
			}

			resolvedBag, err := cardsResolveBagIDFunc(bagID)
			if err != nil {
				return err
			}

			if jsonFlag.Used && len(jsonFlag.Fields) == 0 {
				common.PrintFieldList(cardsGetFields)
				return nil
			}

			ctx := cmd.Context()
			client, user, err := cardsAuthenticatedClientFunc(ctx)
			if err != nil {
				return err
			}

			card, err := cardsGetCardFunc(ctx, client, user.ID, resolvedBag, cardID)
			if err != nil {
				return err
			}

			payload := cardOutputPayload(*card, resolvedBag)
			if handled, err := jsonFlag.HandleOutput(payload, cardsGetFields); handled {
				return err
			}

			printCardOutput(*card, resolvedBag)
			return nil
		},
	}

	cmd.Flags().StringVar(&bagID, "bag", "", "Target bag ID. Falls back to default_bag_id in the config file.")
	return cmd
}

func newCardsReplaceCmd() *cobra.Command {
	var (
		bagID       string
		question    string
		answer      string
		hint        string
		explanation string
		contextText string
	)

	cmd := &cobra.Command{
		Use:   "replace <card-id>",
		Short: "Replace flashcard content and reset its schedule",
		Long: `Replace a flashcard's study content, then reset its FSRS
schedule to the initial new-card state. This is intended for prompt
quality migrations where changing the question or hint should make
the card behave like a newly introduced card.

The command fetches the existing card first. If --answer,
--explanation, or --context is omitted, the current value is preserved.
The --question and --hint flags are required because they are the
fields usually being regenerated by the skill.`,
		Example: `  ep cards replace kx78x72vmrhxft4gdd38z7s4yd81bscy \
    --question "I felt ___ after reading the rejection letter." \
    --hint "discouraged, dejected, low-spirited"

  ep cards replace kx78x72vmrhxft4gdd38z7s4yd81bscy --bag k17abc... \
    --answer "disheartened" \
    --question "I felt ___ after reading the rejection letter." \
    --hint "discouraged, dejected, low-spirited" \
    --json`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cardID := strings.TrimSpace(args[0])
			if cardID == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"card-id is required",
					nil,
				)
			}
			if strings.TrimSpace(question) == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"--question is required",
					nil,
				)
			}
			if strings.TrimSpace(hint) == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"--hint is required",
					nil,
				)
			}
			if cmd.Flags().Changed("answer") && strings.TrimSpace(answer) == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"--answer must not be blank when provided",
					nil,
				)
			}

			resolvedBag, err := cardsResolveBagIDFunc(bagID)
			if err != nil {
				return err
			}

			if jsonFlag.Used && len(jsonFlag.Fields) == 0 {
				common.PrintFieldList(append(
					[]common.Field{{Name: "ok", Type: "boolean"}},
					cardsReplaceFields...,
				))
				return nil
			}

			ctx := cmd.Context()
			client, user, err := cardsAuthenticatedClientFunc(ctx)
			if err != nil {
				return err
			}

			existing, err := cardsGetCardFunc(ctx, client, user.ID, resolvedBag, cardID)
			if err != nil {
				return err
			}

			nextAnswer := strings.TrimSpace(answer)
			if nextAnswer == "" {
				nextAnswer = existing.Answer
			}

			nextExplanation := existing.Explanation
			if cmd.Flags().Changed("explanation") {
				value := strings.TrimSpace(explanation)
				nextExplanation = &value
			}

			nextContext := existing.Context
			if cmd.Flags().Changed("context") {
				value := strings.TrimSpace(contextText)
				nextContext = &value
			}

			replacement := cardReplacement{
				Question:    strings.TrimSpace(question),
				Answer:      nextAnswer,
				Hint:        strings.TrimSpace(hint),
				Explanation: nextExplanation,
				Context:     nextContext,
				SourceWord:  existing.SourceWord,
				Expression:  existing.Expression,
			}
			if err := cardsReplaceCardContentAndResetScheduleFunc(ctx, client, resolvedBag, cardID, replacement); err != nil {
				return err
			}

			card := cardDetail{
				ID:          existing.ID,
				Question:    replacement.Question,
				Answer:      replacement.Answer,
				Hint:        &replacement.Hint,
				Explanation: replacement.Explanation,
				Context:     replacement.Context,
				SourceWord:  replacement.SourceWord,
				Expression:  replacement.Expression,
			}
			payload := cardOutputPayload(card, resolvedBag)
			if handled, err := jsonFlag.HandleOKOutput(payload, cardsReplaceFields); handled {
				return err
			}

			fmt.Printf("Replaced card %s in bag %s and reset its schedule:\n", cardID, resolvedBag)
			fmt.Printf("  Q: %s\n", replacement.Question)
			fmt.Printf("  A: %s\n", replacement.Answer)
			fmt.Printf("  Hint: %s\n", replacement.Hint)
			return nil
		},
	}

	cmd.Flags().StringVar(&bagID, "bag", "", "Target bag ID. Falls back to default_bag_id in the config file.")
	cmd.Flags().StringVar(&question, "question", "", "Replacement fill-in-the-blank question with ___ for the answer. Required.")
	cmd.Flags().StringVar(&answer, "answer", "", "Replacement answer. Defaults to the current answer when omitted.")
	cmd.Flags().StringVar(&hint, "hint", "", "Replacement hint, usually 2-3 short synonyms or paraphrases. Required.")
	cmd.Flags().StringVar(&explanation, "explanation", "", "Replacement explanation. Defaults to the current explanation when omitted.")
	cmd.Flags().StringVar(&contextText, "context", "", "Replacement context. Defaults to the current context when omitted.")
	return cmd
}

func newCardsDeleteCmd() *cobra.Command {
	var bagID string

	cmd := &cobra.Command{
		Use:   "delete <card-id>",
		Short: "Soft-delete a flashcard",
		Long: `Soft-delete a flashcard by id. Calls the Convex
learning:deleteCard mutation, which marks the card with deletedAt
and decrements the bag's per-state counters.

The --bag flag is optional and falls back to default_bag_id in
the config file (set via 'ep bags default set'). The mutation
requires both cardId AND bagId, so a card from a non-default bag
must be deleted with --bag explicitly.

Idempotent: deleting a non-existent or already-deleted card is a
no-op and returns successfully. The skill should treat the
absence of the card as success on retry.`,
		Example: `  # Delete a card in the default bag
  ep cards delete kx78x72vmrhxft4gdd38z7s4yd81bscy

  # Explicit bag
  ep cards delete kx78x72vmrhxft4gdd38z7s4yd81bscy --bag k17abc...

  # JSON output (emits {"ok": true, "cardId": ..., "bagId": ...})
  ep cards delete kx78x72vmrhxft4gdd38z7s4yd81bscy --json`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cardID := strings.TrimSpace(args[0])
			if cardID == "" {
				return common.NewTokenError(
					common.TokenMissingRequiredField,
					"card-id is required",
					nil,
				)
			}

			resolvedBag, err := resolveBagID(bagID)
			if err != nil {
				return err
			}

			if jsonFlag.Used && len(jsonFlag.Fields) == 0 {
				common.PrintFieldList(append(
					[]common.Field{{Name: "ok", Type: "boolean"}},
					cardsDeleteFields...,
				))
				return nil
			}

			ctx := cmd.Context()

			client, _, err := authenticatedClient(ctx)
			if err != nil {
				return err
			}

			if _, err := client.Mutation(ctx, "learning:deleteCard", map[string]any{
				"cardId": cardID,
				"bagId":  resolvedBag,
			}); err != nil {
				return err
			}

			payload := map[string]any{
				"cardId": cardID,
				"bagId":  resolvedBag,
			}
			if handled, err := jsonFlag.HandleOKOutput(payload, cardsDeleteFields); handled {
				return err
			}

			fmt.Printf("Deleted card %s from bag %s\n", cardID, resolvedBag)
			return nil
		},
	}

	cmd.Flags().StringVar(&bagID, "bag", "", "Target bag ID. Falls back to default_bag_id in the config file.")
	return cmd
}
