# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ep < Formula
  desc "CLI for English Punch flashcard app"
  homepage "https://github.com/englishpunch/english-punch-app"
  version "0.3.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/englishpunch/english-punch-app/releases/download/v0.3.1/ep_darwin_amd64.tar.gz"
    sha256 "6e4031b4cb4aa4c6ebfe7be5a69f75024c525ea52589c9435c8a76649f82729a"

    define_method(:install) do
      bin.install "ep"
      generate_completions_from_executable(bin/"ep", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/englishpunch/english-punch-app/releases/download/v0.3.1/ep_darwin_arm64.tar.gz"
    sha256 "01500d104a6fec68cb0df886040085aa11be0488425a726f1a86eeb999fa36ac"

    define_method(:install) do
      bin.install "ep"
      generate_completions_from_executable(bin/"ep", "completion")
    end
  end
end
