# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ep < Formula
  desc "CLI for English Punch flashcard app"
  homepage "https://github.com/englishpunch/english-punch-app"
  version "0.3.12"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/englishpunch/english-punch-app/releases/download/v0.3.12/ep_darwin_amd64.tar.gz"
    sha256 "2ba8c7d1cf1dbcd305d322ab0ddd69a309bc4028d716fdb5b809b09649b8067c"

    define_method(:install) do
      bin.install "ep"
      generate_completions_from_executable(bin/"ep", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/englishpunch/english-punch-app/releases/download/v0.3.12/ep_darwin_arm64.tar.gz"
    sha256 "079f60200b2a40d40c2c916c6bf615295095ac58f3107b901082298df43841e8"

    define_method(:install) do
      bin.install "ep"
      generate_completions_from_executable(bin/"ep", "completion")
    end
  end
end
