#!/usr/bin/env node
/**
 * Generates Go types and field definitions from Convex query return validators.
 *
 * Usage: node cli/codegen/generate.mjs > cli/internal/ep/cmd/types_gen.go
 *
 * Source of truth: Convex `returns` validators in convex/learning.ts
 */

import { v } from "convex/values";

// ── Define schemas to generate ──────────────────────────────────────────────
// Each entry maps a Go type name to its Convex validator.
// Add new entries here when new CLI commands need typed output.

const schemas = {
  Bag: {
    validator: v.object({
      _id: v.id("bags"),
      name: v.string(),
      description: v.optional(v.string()),
      totalCards: v.number(),
      newCards: v.number(),
      learningCards: v.number(),
      reviewCards: v.number(),
      tags: v.array(v.string()),
      isActive: v.boolean(),
    }),
    // Source: convex/learning.ts getUserBags returns
  },
};

// ── Convex type → Go type mapping ───────────────────────────────────────────

function convexTypeToGo(fieldType) {
  switch (fieldType.type) {
    case "string":
      return { goType: "string", fieldType: "string" };
    case "number":
      return { goType: "float64", fieldType: "number" };
    case "boolean":
      return { goType: "bool", fieldType: "boolean" };
    case "id":
      return { goType: "string", fieldType: "string" };
    case "array": {
      const inner = convexTypeToGo(fieldType.value);
      return { goType: `[]${inner.goType}`, fieldType: `${inner.fieldType}[]` };
    }
    case "null":
      return { goType: "any", fieldType: "null" };
    case "object":
      return { goType: "map[string]any", fieldType: "object" };
    default:
      return { goType: "any", fieldType: "any" };
  }
}

// ── Go code generation ──────────────────────────────────────────────────────

function generateStruct(name, validator) {
  const schema = validator.json;
  if (schema.type !== "object") {
    throw new Error(`Expected object validator for ${name}, got ${schema.type}`);
  }

  const fields = [];
  for (const [fieldName, fieldDef] of Object.entries(schema.value)) {
    const { goType, fieldType } = convexTypeToGo(fieldDef.fieldType);
    const optional = fieldDef.optional;

    // Go struct field name: capitalize first letter, keep rest
    const goFieldName =
      fieldName === "_id"
        ? "ID"
        : fieldName.charAt(0).toUpperCase() + fieldName.slice(1);

    const jsonTag = optional
      ? `\`json:"${fieldName},omitempty"\``
      : `\`json:"${fieldName}"\``;

    fields.push({ goFieldName, goType, jsonTag, fieldName, fieldType, optional });
  }

  return fields;
}

function emit() {
  const lines = [];
  lines.push("// Code generated by cli/codegen/generate.mjs. DO NOT EDIT.");
  lines.push("");
  lines.push("package cmd");
  lines.push("");
  lines.push('import "github.com/echoja/english-punch-app/cli/internal/ep/common"');
  lines.push("");

  for (const [name, { validator }] of Object.entries(schemas)) {
    const fields = generateStruct(name, validator);
    const lowerName = name.charAt(0).toLowerCase() + name.slice(1);

    // Struct
    lines.push(`type ${lowerName} struct {`);
    // Calculate padding for alignment
    const maxNameLen = Math.max(...fields.map((f) => f.goFieldName.length));
    const maxTypeLen = Math.max(...fields.map((f) => f.goType.length));
    for (const f of fields) {
      const namePad = f.goFieldName.padEnd(maxNameLen);
      const typePad = f.goType.padEnd(maxTypeLen);
      lines.push(`\t${namePad} ${typePad} ${f.jsonTag}`);
    }
    lines.push("}");
    lines.push("");

    // Field list
    lines.push(`var ${lowerName}Fields = []common.Field{`);
    for (const f of fields) {
      lines.push(`\t{Name: "${f.fieldName}", Type: "${f.fieldType}"},`);
    }
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

console.log(emit());
